# Backend CI - .NET Workflow
#
# Este workflow ejecuta CI para el backend .NET siguiendo TRUST 5:
# - Trazabilidad: Reportes de tests y coverage
# - Repetibilidad: Build determinístico
# - Uniformidad: Mismos pasos en local y CI
# - Seguridad: Dependency scanning
# - Testabilidad: Unit + Integration tests
#
# Triggers:
# - Push a main/develop
# - Pull requests
# - Manual dispatch

name: Backend CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'tests/**'
      - '**.csproj'
      - '**.sln'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'tests/**'
      - '**.csproj'
      - '**.sln'
  workflow_dispatch:
    inputs:
      run_integration_tests:
        description: 'Ejecutar tests de integración'
        required: false
        default: 'true'
        type: boolean

env:
  DOTNET_VERSION: '8.0.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  # Job 1: Build y validación básica
  build:
    name: Build y compilación
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Para análisis de código

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            src/**/bin/Release
            !src/**/bin/Release/**/*.pdb
          retention-days: 1

  # Job 2: Tests unitarios
  unit-tests:
    name: Tests unitarios
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Run unit tests
        run: |
          dotnet test \
            --configuration Release \
            --no-restore \
            --filter "Category=Unit" \
            --collect:"XPlat Code Coverage" \
            --logger "trx;LogFileName=unit-test-results.trx" \
            --results-directory ./TestResults

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: TestResults/*.trx
          retention-days: 7

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage
          path: TestResults/**/coverage.cobertura.xml
          retention-days: 7

      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: always()
        with:
          filename: TestResults/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && always()
        with:
          recreate: true
          path: code-coverage-results.md

  # Job 3: Tests de integración (con Testcontainers)
  integration-tests:
    name: Tests de integración
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.event.inputs.run_integration_tests == 'true'

    services:
      # PostgreSQL para tests
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Run integration tests
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=testdb;Username=testuser;Password=testpass"
        run: |
          dotnet test \
            --configuration Release \
            --no-restore \
            --filter "Category=Integration" \
            --collect:"XPlat Code Coverage" \
            --logger "trx;LogFileName=integration-test-results.trx" \
            --results-directory ./TestResults

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: TestResults/*.trx
          retention-days: 7

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-coverage
          path: TestResults/**/coverage.cobertura.xml
          retention-days: 7

  # Job 4: Security scanning
  security:
    name: Security scanning
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Run .NET security scan
        run: |
          dotnet list package --vulnerable --include-transitive 2>&1 | tee security-scan.txt

      - name: Check for vulnerabilities
        run: |
          if grep -q "has the following vulnerable packages" security-scan.txt; then
            echo "❌ Vulnerabilidades encontradas"
            cat security-scan.txt
            exit 1
          else
            echo "✅ No se encontraron vulnerabilidades"
          fi

      - name: Upload security scan results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-scan
          path: security-scan.txt
          retention-days: 7

  # Job 5: Code quality analysis
  code-quality:
    name: Análisis de calidad
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Para análisis completo

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Run dotnet format check
        run: dotnet format --verify-no-changes --verbosity diagnostic
        continue-on-error: true

      - name: Install dotnet-outdated
        run: dotnet tool install --global dotnet-outdated-tool

      - name: Check for outdated packages
        run: dotnet outdated --fail-on-updates
        continue-on-error: true

  # Job 6: Build Docker image (opcional)
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, security]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            myapp-backend:${{ github.sha }}
            myapp-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_CONFIGURATION=Release

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp-backend:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  # Job 7: Status check final
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [build, unit-tests, integration-tests, security, code-quality]
    if: always()

    steps:
      - name: Check CI status
        run: |
          if [ "${{ needs.build.result }}" != "success" ] || \
             [ "${{ needs.unit-tests.result }}" != "success" ] || \
             [ "${{ needs.integration-tests.result }}" != "success" ] || \
             [ "${{ needs.security.result }}" != "success" ]; then
            echo "❌ CI failed - revisar logs"
            exit 1
          else
            echo "✅ CI completado exitosamente"
          fi
